<?php
/**
 * Created S/14/04/2018
 * Updated S/19/02/2022
 *
 * Copyright 2011-2023 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://github.com/luigifab/openmage-minifier
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$script = sprintf('\'%slocale/\' + this.value + \'/%s/%s\'', $this->getChangeLocaleUrl(), $this->getRefererParamName(), $this->getUrlForReferer());
?>

<p class="bug-report"><?php echo $this->__('Interface Locale: %s', str_replace(
	[' class=""', 'width:200px">', '<select', ' title="'.$this->helper('page')->__('Interface Language').'"'],
	['', 'width:300px;"><option></option>', '<select onchange="setLocation('.$script.');"', ''],
	$this->getLanguageSelect()
)) ?></p>

<p class="legality"><a href="https://github.com/OpenMage/magento-lts">OpenMage <?php echo Mage::getOpenMageVersion() ?></a></p>
<?php echo $this->getChildHtml() ?>