<?php
/**
 * Created S/14/04/2018
 * Updated S/26/06/2021
 *
 * Copyright 2011-2022 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/openmage/minifier
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$onchange = sprintf('\'%slocale/\' + this.value + \'/%s/%s\'', $this->getChangeLocaleUrl(), $this->getRefererParamName(), $this->getUrlForReferer());
?>

<p class="bug-report"><?php echo $this->__('Interface Locale: %s', str_replace(
	[' class=""', 'width:200px">', '<select'],
	['', 'width:300px;"><option></option>', '<select onchange="setLocation('.$onchange.');"'],
	$this->getLanguageSelect()
)) ?></p>

<p class="legality">OpenMage <?php echo Mage::getOpenMageVersion() ?></p>
<?php echo $this->getChildHtml() ?>