<?php
/**
 * Created S/14/04/2018
 * Updated J/20/05/2021
 *
 * Copyright 2011-2022 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/openmage/minifier
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$database = Mage::getSingleton('core/resource')->getConnection('core_read')->fetchOne('SELECT VERSION()');
$browser  = $this->helper('core')->isModuleEnabled('Luigifab_Apijs') ? Mage::getSingleton('apijs/useragentparser')->parse() : null;

$session = (string) Mage::getConfig()->getNode('global/session_save');
if (in_array($session, ['db', 'redis']) && $this->helper('core')->isModuleEnabled('Cm_RedisSession') &&
	Mage::getConfig()->getNode('global/redis_session') && Mage::getSingleton('Cm_RedisSession_Model_Session')->hasConnection())
	$session = 'redis';

$cache = (string) Mage::getConfig()->getNode('global/cache/backend');
$cache = (mb_stripos($cache, 'redis') !== false) ? 'redis' : (empty($cache) ? 'files' : $cache);
?>

<div class="header-top minifier" style="height:55px; color:white; border:0;">
	<a href="<?php echo $this->getHomeLink() ?>">
		<img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="" class="logo" style="height:43px;" />
	</a>
	<div class="header-right">
		<p style="margin:0; font-size:11px; line-height:150%;">
			<strong><?php echo ucfirst($this->formatDate(null, 'full', true)) ?></strong>
			// <a href="<?php echo $this->getUrl('*/system_account/index') ?>" style="color:white; text-decoration:none;">
				<?php echo str_replace('<strong', '<strong style="text-decoration:underline;"', $this->__('Logged in as %s', $this->getUser()->getData('username'))) ?> (<?php echo $this->getUser()->getRole()->getData('role_name') ?>)
			</a>
			<?php if (!empty($browser)): ?>
				// <?php echo sprintf('%s %d (%s)', $browser['browser'], $browser['version'], $browser['platform']) ?>
			<?php endif ?>
			// <a href="<?php echo $this->getLogoutLink() ?>" class="logout"><?php echo $this->__('Log Out') ?></a>
			<br />
			<?php if (Mage::getIsDeveloperMode()): ?>
				<strong>dev:on</strong> <?php echo trim($this->helper('minifier')->getKeyForUrls(), '-') ?> //
			<?php endif ?>
			<?php echo implode(' ', array_map(static function ($value) { return number_format($value, 2); }, sys_getloadavg())) ?> //
			OpenMage <?php echo Mage::getOpenMageVersion() ?> //
			<abbr>PHP</abbr> <?php echo implode('.', array_slice(preg_split('#\D#', PHP_VERSION), 0, 3)) ?> //
			<abbr><?php echo $this->__('DB') ?></abbr> <?php echo implode('.', array_slice(preg_split('#\D#', $database), 0, 3)) ?> //
			Session <?php echo $session ?> //
			Cache <?php echo $cache ?>
		</p>
	</div>
</div>