<?php
/**
 * Created S/14/04/2018
 * Updated D/03/12/2023
 *
 * Copyright 2011-2024 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://github.com/luigifab/openmage-minifier
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$config    = Mage::getConfig();
$browser   = Mage::getSingleton('minifier/useragentparser')->parse();
$dbVersion = Mage::getSingleton('core/resource')->getConnection('core_read')->fetchOne('SELECT VERSION()');
$session   = (string) $config->getNode('global/session_save');

if (in_array($session, ['db', 'redis']) && $this->helper('core')->isModuleEnabled('Cm_RedisSession') && $config->getNode('global/redis_session')) {
	try {
		$model = Mage::getSingleton('Cm_RedisSession_Model_Session');
		if (method_exists($model, 'hasConnection') && $model->hasConnection())
			$session = 'redis';
		else if (method_exists($model, 'getInfo') && $model->getInfo())
			$session = 'redis';
		if ($session == 'redis')
			$session .= ' (db:'.((string) $config->getNode('global/redis_session/db')).')';
	}
	catch (Throwable $t) { }
}

$cache = (string) $config->getNode('global/cache/backend');
$cache = (stripos($cache, 'redis') !== false) ? 'redis' : (empty($cache) ? 'files' : $cache);
if ($cache == 'redis')
	$cache .= ' (db:'.((string) $config->getNode('global/cache/backend_options/database')).')';

// ount!!!! ~40ms
$jit = function_exists('opcache_get_status') ? opcache_get_status() : [];
?>

<div class="header-top minifier" style="height:55px; color:white; border:0;">
	<a href="<?php echo $this->getHomeLink() ?>">
		<?php if (is_file(Mage::getBaseDir('skin').'/adminhtml/default/default/images/logo.svg')): ?>
			<img src="<?php echo $this->getSkinUrl('images/logo.svg') ?>" alt="OpenMage" class="logo" style="margin:10px 32px; height:35px;" />
		<?php else: ?>
			<img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="OpenMage" class="logo" style="height:43px;" />
		<?php endif ?>
	</a>
	<div class="header-right">
		<p style="margin:0; font-size:11px; line-height:150%;">
			<?php echo ucfirst($this->formatDate(null, 'full', true)) ?>
			<?php if (Mage::getIsDeveloperMode()): ?>
				(<?php echo date('H:i:s') ?> utc)
			<?php endif ?>
			// <a href="<?php echo $this->getUrl('*/system_account/index') ?>" style="color:white; text-decoration:none;">
				<?php echo str_replace('<strong', '<strong style="text-decoration:underline;"', $this->__('Logged in as %s', $this->getUser()->getData('username'))) ?> (<?php echo $this->getUser()->getRole()->getData('role_name') ?>)
			</a>
			<?php if (!empty($browser)): ?>
				// <?php echo sprintf('%s %d (%s)', $browser['browser'], $browser['version'], $browser['platform']) ?>
			<?php endif ?>
			// <a href="<?php echo $this->getLogoutLink() ?>" class="logout"><?php echo $this->__('Log Out') ?></a>
			<br />
			<?php if (Mage::getIsDeveloperMode()): ?>
				<strong>dev:on</strong> //
			<?php endif ?>
			<?php echo implode(' ', array_map(static function ($value) { return number_format($value, 2); }, sys_getloadavg())) ?> //
			OpenMage <?php echo Mage::getOpenMageVersion() ?>
			// <abbr>PHP</abbr> <?php echo implode('.', array_slice(preg_split('#\D#', PHP_VERSION), 0, 3)) ?>
			<?php if (!empty($jit['jit']['enabled']) && !empty($jit = ini_get('opcache.jit')) && (strlen($jit) >= 4)):
				if ($jit == 'tracing')
					$jit = 1254;
				else if ($jit == 'function')
					$jit = 1205;
				// @see https://wiki.php.net/rfc/jit#phpini_defaults (23 june 2023)
				// opcache.jit - JIT control options, consists of 4 decimal digits, CRTO (Default 1205)
				$info  = '<abbr title="C - CPU specific optimization flags: ';
				if ($jit[0] == '0')
					$info .= '0 - none">0';
				else if ($jit[0] == '1')
					$info .= '1 - enable AVX instruction generation">1';
				else
					$info .= 'unknown">'.$jit[0];
				$info .= '</abbr><abbr title="R - register allocation: ';
				if ($jit[1] == '0')
					$info .= '0 - don\'t perform register allocation">0';
				else if ($jit[1] == '1')
					$info .= '1 - use local liner-scan register allocator">1';
				else if ($jit[1] == '2')
					$info .= '2 - use global liner-scan register allocator">2';
				else
					$info .= 'unknown">'.$jit[1];
				$info .= '</abbr><abbr title="T - JIT trigger: ';
				if ($jit[2] == '0')
					$info .= '0 - JIT all functions on first script load">0';
				else if ($jit[2] == '1')
					$info .= '1 - JIT function on first execution">1';
				else if ($jit[2] == '2')
					$info .= '2 - Profile on first request and compile hot functions on second request">2';
				else if ($jit[2] == '3')
					$info .= '3 - Profile on the fly and compile hot functions">3';
				else if ($jit[2] == '4')
					$info .= '4 - Compile functions with @jit tag in doc-comments">4';
				else
					$info .= 'unknown">'.$jit[2];
				$info .= '</abbr><abbr title="O - Optimization level: ';
				if ($jit[3] == '0')
					$info .= '0 - don\'t JIT">0';
				else if ($jit[3] == '1')
					$info .= '1 - minimal JIT (call standard VM handlers)">1';
				else if ($jit[3] == '2')
					$info .= '2 - selective VM handler inlining">2';
				else if ($jit[3] == '3')
					$info .= '3 - optimized JIT based on static type inference of individual function">3';
				else if ($jit[3] == '4')
					$info .= '4 - optimized JIT based on static type inference and call tree">4';
				else if ($jit[3] == '5')
					$info .= '5 - optimized JIT based on static type inference and inner procedure analyses">5';
				else
					$info .= 'unknown">'.$jit[3];
				$info .= '</abbr>';
			?>
				(JIT <?php echo $info ?> <?php echo ini_get('opcache.jit_buffer_size') ?>)
			<?php endif ?>
			// <abbr><?php echo $this->__('DB') ?></abbr> <?php echo implode('.', array_slice(preg_split('#\D#', $dbVersion), 0, 3)) ?>
			<?php if (Mage::getIsDeveloperMode()): ?>
				(<?php echo $config->getNode('global/resources/default_setup/connection/dbname') ?>)
			<?php endif ?>
			// Session <?php echo $session ?>
			// Cache <?php echo $cache ?>
		</p>
	</div>
</div>