<?php
/**
 * Created J/26/07/2018
 * Updated S/19/02/2022
 *
 * Copyright 2011-2022 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/openmage/minifier
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help = $this->helper('minifier');
?>

<title><?php echo $help->escapeEntities(html_entity_decode($this->getTitle())) ?></title>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Language" content="<?php echo $this->getParentBlock()->getLang() ?>" />
<meta name="robots" content="<?php echo $help->escapeEntities($this->getRobots(), true) ?>" />

<?php if (!empty($text = $this->getDescription())): ?>
	<meta name="description" content="<?php echo $help->escapeEntities($text, true) ?>" />
<?php endif ?>
<?php if (!empty($text = $this->getKeywords())): ?>
	<meta name="keywords" content="<?php echo $help->escapeEntities($text, true) ?>" />
<?php endif ?>

<link rel="icon" type="image/x-icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" />
<?php echo $this->getChildHtml('before_cssjs') ?>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml('after_cssjs') ?>
<?php echo $this->getChildHtml() ?>

<?php if (!Mage::getStoreConfigFlag('minifier/cssjs/enabled_front')): ?>
	<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php endif ?>

<?php echo $this->getIncludes() ?>